services:
  postgres-db:
    image: postgres:17-alpine
    container_name: ${POSTGRES_DB}_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel_planner_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - travel-network
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}
      JWT_COOKIE_SECURE: ${JWT_COOKIE_SECURE:-false}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
    container_name: travel_planner_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - travel-network

volumes:
  postgres_data:

networks:
  travel-network:
    driver: bridge